name: CI

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:

  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Check linting
        run: |
          npm run lint
      - name: Run tests
        run: |
          npm test

  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/

  build-ios:
    needs: install-and-test
    runs-on: [self-hosted, macos]
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: Build app
        run: |
          xcodebuild -workspace AltRetrospect.xcworkspace -scheme AltRetrospect archive -archivePath AltRetrospect.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./AltRetrospect.xcarchive -exportPath . -exportOptionsPlist AltRetrospect/Info.plist
          mv AltRetrospect.ipa ../AltRetrospect.ipa
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: AltRetrospect.ipa
          path: ios/build/
